# Generated by Django 2.2.1 on 2019-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nivel', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=300)),
                ('itens', models.ManyToManyField(related_name='itens_delegacao', to='item.Item')),
                ('nivel', models.ManyToManyField(related_name='nivel_delegacao', to='nivel.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Delegações',
            },
        ),
    ]
