# Generated by Django 2.2.1 on 2019-06-07 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegacao',
            options={'verbose_name_plural': 'Delegações'},
        ),
    ]
