# Generated by Django 2.2.1 on 2019-06-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_auto_20190615_1551'),
        ('delegacao', '0002_auto_20190607_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacao',
            name='nivel',
            field=models.ManyToManyField(related_name='nivel_delegacao', to='nivel.Nivel'),
        ),
    ]
