# Generated by Django 2.2.1 on 2019-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_auto_20190615_1551'),
        ('delegacao', '0002_auto_20190607_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegacao',
            name='status',
        ),
        migrations.AddField(
            model_name='delegacao',
            name='nivel',
            field=models.ManyToManyField(related_name='nivel_delegacao', to='nivel.Nivel'),
        ),
        migrations.AlterField(
            model_name='delegacao',
            name='itens',
            field=models.ManyToManyField(related_name='itens_delegacao', to='item.Item'),
        ),
        migrations.AlterField(
            model_name='delegacao',
            name='tipo',
            field=models.CharField(max_length=80),
        ),
    ]
