# Generated by Django 2.2.1 on 2019-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=19)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=17)),
                ('situacao', models.BooleanField(default=True)),
                ('enviado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Organizações',
            },
        ),
    ]
