# Generated by Django 2.2.1 on 2019-07-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
