# Generated by Django 2.2.1 on 2019-05-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name_plural': 'Organizações'},
        ),
    ]
