# Generated by Django 2.2.1 on 2019-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
    ]
