# Generated by Django 2.2.1 on 2019-05-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_organizacao_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='numeroNivel',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
