# Generated by Django 2.2.1 on 2019-06-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_auto_20190607_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='numeroNivel',
        ),
    ]
