# Generated by Django 2.2.1 on 2019-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_remove_organizacao_numeronivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='cnpj',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='telefone',
            field=models.CharField(max_length=17),
        ),
    ]
