# Generated by Django 2.2.1 on 2019-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('situacao', models.BooleanField(default=True)),
                ('numeroNivel', models.CharField(max_length=2)),
            ],
        ),
    ]
