# Generated by Django 2.2.1 on 2019-05-09 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='funcionario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='nivelInferior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nivelinferior', to='nivel.Nivel'),
        ),
        migrations.AddField(
            model_name='nivel',
            name='nivelSuperior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nivelsuperior', to='nivel.Nivel'),
        ),
    ]
