# Generated by Django 2.2.1 on 2019-05-19 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_auto_20190517_1957'),
        ('nivel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='organizacao',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, related_name='organizacao_do_nivel', to='organizacao.Organizacao'),
            preserve_default=False,
        ),
    ]
