# Generated by Django 2.2.1 on 2019-05-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_auto_20190509_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'verbose_name_plural': 'Niveis'},
        ),
    ]
