# Generated by Django 2.2.1 on 2019-05-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20190507_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
    ]
