# Generated by Django 2.2.1 on 2019-05-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_auto_20190508_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='status',
            new_name='ativo',
        ),
    ]
