# Generated by Django 2.2.1 on 2019-05-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=25)),
                ('itens', models.ManyToManyField(related_name='itens_solicitacao', to='solicitacao.Item')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
