# Generated by Django 2.2.1 on 2019-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='itens',
            field=models.ManyToManyField(null=True, related_name='itens_solicitacao', to='solicitacao.Item'),
        ),
    ]
