# Generated by Django 2.2.1 on 2019-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='status',
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(max_length=80),
        ),
    ]
