# Generated by Django 2.2.1 on 2019-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name_plural': 'Solicitações'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='teste',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='item',
            field=models.ManyToManyField(to='solicitacao.Item'),
        ),
    ]
