# Generated by Django 2.2.1 on 2019-05-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(default='tatus', max_length=25),
            preserve_default=False,
        ),
    ]
