# Generated by Django 2.2.1 on 2019-06-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='solicitacaoDelegacao',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
