# Generated by Django 2.2.1 on 2019-05-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20190516_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='item',
            field=models.ManyToManyField(null=True, to='solicitacao.Item'),
        ),
    ]
