# Generated by Django 2.2.1 on 2019-05-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('funcionario', models.ManyToManyField(blank=True, to='funcionario.Funcionario')),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
