# Generated by Django 2.2.1 on 2019-05-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivel', '0002_auto_20190509_2359'),
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nivel.Nivel'),
        ),
    ]
