# Generated by Django 2.2.1 on 2019-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_funcionario_foto'),
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='funcionario',
            field=models.ManyToManyField(blank=True, to='funcionario.Funcionario'),
        ),
    ]
