# Generated by Django 2.2.1 on 2019-05-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0003_setor_gerente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='funcionario',
            field=models.ManyToManyField(blank=True, null=True, to='funcionario.Funcionario'),
        ),
    ]
