# Generated by Django 2.2.1 on 2019-05-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0004_auto_20190510_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='funcionario',
            field=models.ManyToManyField(blank=True, to='funcionario.Funcionario'),
        ),
    ]
