# Generated by Django 2.2.1 on 2019-05-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('senha', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14)),
                ('cargo', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
    ]
