# Generated by Django 2.2.1 on 2019-05-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
