# Generated by Django 2.2.1 on 2019-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=300, null=True)),
                ('tipo', models.CharField(choices=[('int', 'Inteiro'), ('double', 'Real'), ('date', 'Data'), ('text', 'Texto'), ('file', 'Arquivo')], default='text', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('campus', models.ManyToManyField(to='item.Campo')),
            ],
        ),
    ]
