# Generated by Django 2.2.1 on 2019-06-27 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, null=True)),
                ('email', models.EmailField(max_length=80, null=True)),
                ('senha', models.CharField(max_length=65, null=True)),
                ('cpf', models.CharField(max_length=15, null=True)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('telefone', models.CharField(max_length=17, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/funcionario')),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizacao', to='organizacao.Organizacao')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
