# Generated by Django 2.2.1 on 2019-06-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
